### ISSUE TITLE
Build failing on Ubuntu 14.04.3 with Emscripten 1.34.8

### ISSUE THREAD

**Issue by buntine** [rnlf/motor#8]
I've installed Emscripten 1.34.8 and compiled the "Hello, world" tests, which work fine.

I then cloned your repo, created a build directory, moved into it and then issued: "python ../build.py build"

I eventually get the following error:

```
Linking motor2d.js
/home/andrew/dev/javascript/emsdk_portable/clang/tag-e1.34.8/build_tag-e1.34.8_64/bin/opt: /tmp/tmpQpBz4S/motor2d.bc: error: Could not open input file: No such file or directory
Traceback (most recent call last):
  File "/home/andrew/dev/javascript/emsdk_portable/emscripten/tag-1.34.8/emcc", line 1255, in <module>
    final = shared.Building.llvm_opt(in_temp(target_basename + '.bc'), llvm_opts, DEFAULT_FINAL)
  File "/home/andrew/dev/javascript/emsdk_portable/emscripten/tag-1.34.8/tools/shared.py", line 1412, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations: 
Failed
```

Full output here: https://gist.github.com/buntine/2130ba026308b56cbf6e

Have I missed something?

Thanks!

**Comment by Murii** [comment]
Make sure you have clang installed. I guess it's something like : sudo apt-get install clang

**Comment by buntine** [comment]
Thanks for the response.

I installed clang from ubuntu repositories, but same error.

It looks like it's using the clang that emscripten built for me?

**Comment by Murii** [comment]
Have you compiled/installed : emscripten-fastcomp?

**Comment by buntine** [comment]
This one: https://github.com/kripken/emscripten-fastcomp ??

No, do I need to?

**Comment by Murii** [comment]
Yeah you need that one in order to transform cpp code into js.

**Comment by buntine** [comment]
Yep, I already have emscripten installed. See above. I've compiled the cpp and c examples to JS on my local machine. My emscripten is working correctly.
